// <auto-generated/>
using System.Collections.Generic;
using System.Linq;
using static NStandard.Measures.StorageCapacity;

namespace NStandard.Measures;

public static class StorageCapacity
{
	public struct b(double value) : IMeasurable<double>
	{
		public double Value { get; set; } = value;

		public static b operator +(b left, b right) => new(left.Value + right.Value);
		public static b operator -(b left, b right) => new(left.Value - right.Value);
		public static b operator *(b left, double right) => new(left.Value * right);
		public static b operator /(b left, double right) => new(left.Value / right);
		public static b operator /(b left, b right) => left.Value / right.Value;
        
		public static bool operator ==(b left, b right) => left.Value == right.Value;
		public static bool operator !=(b left, b right) => left.Value != right.Value;
		public static bool operator <(b left, b right) => left.Value < right.Value;
		public static bool operator <=(b left, b right) => left.Value <= right.Value;
		public static bool operator >(b left, b right) => left.Value > right.Value;
		public static bool operator >=(b left, b right) => left.Value >= right.Value;
        
		public static explicit operator b(kb other) => new(other.Value * 1024);
		public static explicit operator b(mb other) => new(other.Value * 1048576);
		public static explicit operator b(gb other) => new(other.Value * 1073741824);
		public static explicit operator b(tb other) => new(other.Value * 1099511627776);
		public static explicit operator b(pb other) => new(other.Value * 1125899906842624);
		public static explicit operator b(B other) => new(other.Value * 8);
		public static explicit operator b(KB other) => new(other.Value * 8192);
		public static explicit operator b(MB other) => new(other.Value * 8388608);
		public static explicit operator b(GB other) => new(other.Value * 8589934592);
		public static explicit operator b(TB other) => new(other.Value * 8796093022208);
		public static explicit operator b(PB other) => new(other.Value * 9007199254740992);
        public static implicit operator b(double value) => new b(value);

		public override string ToString() => $"{Value} b";
	}

	public struct kb(double value) : IMeasurable<double>
	{
		public double Value { get; set; } = value;

		public static kb operator +(kb left, kb right) => new(left.Value + right.Value);
		public static kb operator -(kb left, kb right) => new(left.Value - right.Value);
		public static kb operator *(kb left, double right) => new(left.Value * right);
		public static kb operator /(kb left, double right) => new(left.Value / right);
		public static kb operator /(kb left, kb right) => left.Value / right.Value;
        
		public static bool operator ==(kb left, kb right) => left.Value == right.Value;
		public static bool operator !=(kb left, kb right) => left.Value != right.Value;
		public static bool operator <(kb left, kb right) => left.Value < right.Value;
		public static bool operator <=(kb left, kb right) => left.Value <= right.Value;
		public static bool operator >(kb left, kb right) => left.Value > right.Value;
		public static bool operator >=(kb left, kb right) => left.Value >= right.Value;
        
		public static explicit operator kb(b other) => new(other.Value / 1024);
		public static explicit operator kb(mb other) => new(other.Value * 1024);
		public static explicit operator kb(gb other) => new(other.Value * 1048576);
		public static explicit operator kb(tb other) => new(other.Value * 1073741824);
		public static explicit operator kb(pb other) => new(other.Value * 1099511627776);
		public static explicit operator kb(B other) => new(other.Value / 128);
		public static explicit operator kb(KB other) => new(other.Value * 8);
		public static explicit operator kb(MB other) => new(other.Value * 8192);
		public static explicit operator kb(GB other) => new(other.Value * 8388608);
		public static explicit operator kb(TB other) => new(other.Value * 8589934592);
		public static explicit operator kb(PB other) => new(other.Value * 8796093022208);
        public static implicit operator kb(double value) => new kb(value);

		public override string ToString() => $"{Value} kb";
	}

	public struct mb(double value) : IMeasurable<double>
	{
		public double Value { get; set; } = value;

		public static mb operator +(mb left, mb right) => new(left.Value + right.Value);
		public static mb operator -(mb left, mb right) => new(left.Value - right.Value);
		public static mb operator *(mb left, double right) => new(left.Value * right);
		public static mb operator /(mb left, double right) => new(left.Value / right);
		public static mb operator /(mb left, mb right) => left.Value / right.Value;
        
		public static bool operator ==(mb left, mb right) => left.Value == right.Value;
		public static bool operator !=(mb left, mb right) => left.Value != right.Value;
		public static bool operator <(mb left, mb right) => left.Value < right.Value;
		public static bool operator <=(mb left, mb right) => left.Value <= right.Value;
		public static bool operator >(mb left, mb right) => left.Value > right.Value;
		public static bool operator >=(mb left, mb right) => left.Value >= right.Value;
        
		public static explicit operator mb(b other) => new(other.Value / 1048576);
		public static explicit operator mb(kb other) => new(other.Value / 1024);
		public static explicit operator mb(gb other) => new(other.Value * 1024);
		public static explicit operator mb(tb other) => new(other.Value * 1048576);
		public static explicit operator mb(pb other) => new(other.Value * 1073741824);
		public static explicit operator mb(B other) => new(other.Value / 131072);
		public static explicit operator mb(KB other) => new(other.Value / 128);
		public static explicit operator mb(MB other) => new(other.Value * 8);
		public static explicit operator mb(GB other) => new(other.Value * 8192);
		public static explicit operator mb(TB other) => new(other.Value * 8388608);
		public static explicit operator mb(PB other) => new(other.Value * 8589934592);
        public static implicit operator mb(double value) => new mb(value);

		public override string ToString() => $"{Value} mb";
	}

	public struct gb(double value) : IMeasurable<double>
	{
		public double Value { get; set; } = value;

		public static gb operator +(gb left, gb right) => new(left.Value + right.Value);
		public static gb operator -(gb left, gb right) => new(left.Value - right.Value);
		public static gb operator *(gb left, double right) => new(left.Value * right);
		public static gb operator /(gb left, double right) => new(left.Value / right);
		public static gb operator /(gb left, gb right) => left.Value / right.Value;
        
		public static bool operator ==(gb left, gb right) => left.Value == right.Value;
		public static bool operator !=(gb left, gb right) => left.Value != right.Value;
		public static bool operator <(gb left, gb right) => left.Value < right.Value;
		public static bool operator <=(gb left, gb right) => left.Value <= right.Value;
		public static bool operator >(gb left, gb right) => left.Value > right.Value;
		public static bool operator >=(gb left, gb right) => left.Value >= right.Value;
        
		public static explicit operator gb(b other) => new(other.Value / 1073741824);
		public static explicit operator gb(kb other) => new(other.Value / 1048576);
		public static explicit operator gb(mb other) => new(other.Value / 1024);
		public static explicit operator gb(tb other) => new(other.Value * 1024);
		public static explicit operator gb(pb other) => new(other.Value * 1048576);
		public static explicit operator gb(B other) => new(other.Value / 134217728);
		public static explicit operator gb(KB other) => new(other.Value / 131072);
		public static explicit operator gb(MB other) => new(other.Value / 128);
		public static explicit operator gb(GB other) => new(other.Value * 8);
		public static explicit operator gb(TB other) => new(other.Value * 8192);
		public static explicit operator gb(PB other) => new(other.Value * 8388608);
        public static implicit operator gb(double value) => new gb(value);

		public override string ToString() => $"{Value} gb";
	}

	public struct tb(double value) : IMeasurable<double>
	{
		public double Value { get; set; } = value;

		public static tb operator +(tb left, tb right) => new(left.Value + right.Value);
		public static tb operator -(tb left, tb right) => new(left.Value - right.Value);
		public static tb operator *(tb left, double right) => new(left.Value * right);
		public static tb operator /(tb left, double right) => new(left.Value / right);
		public static tb operator /(tb left, tb right) => left.Value / right.Value;
        
		public static bool operator ==(tb left, tb right) => left.Value == right.Value;
		public static bool operator !=(tb left, tb right) => left.Value != right.Value;
		public static bool operator <(tb left, tb right) => left.Value < right.Value;
		public static bool operator <=(tb left, tb right) => left.Value <= right.Value;
		public static bool operator >(tb left, tb right) => left.Value > right.Value;
		public static bool operator >=(tb left, tb right) => left.Value >= right.Value;
        
		public static explicit operator tb(b other) => new(other.Value / 1099511627776);
		public static explicit operator tb(kb other) => new(other.Value / 1073741824);
		public static explicit operator tb(mb other) => new(other.Value / 1048576);
		public static explicit operator tb(gb other) => new(other.Value / 1024);
		public static explicit operator tb(pb other) => new(other.Value * 1024);
		public static explicit operator tb(B other) => new(other.Value / 137438953472);
		public static explicit operator tb(KB other) => new(other.Value / 134217728);
		public static explicit operator tb(MB other) => new(other.Value / 131072);
		public static explicit operator tb(GB other) => new(other.Value / 128);
		public static explicit operator tb(TB other) => new(other.Value * 8);
		public static explicit operator tb(PB other) => new(other.Value * 8192);
        public static implicit operator tb(double value) => new tb(value);

		public override string ToString() => $"{Value} tb";
	}

	public struct pb(double value) : IMeasurable<double>
	{
		public double Value { get; set; } = value;

		public static pb operator +(pb left, pb right) => new(left.Value + right.Value);
		public static pb operator -(pb left, pb right) => new(left.Value - right.Value);
		public static pb operator *(pb left, double right) => new(left.Value * right);
		public static pb operator /(pb left, double right) => new(left.Value / right);
		public static pb operator /(pb left, pb right) => left.Value / right.Value;
        
		public static bool operator ==(pb left, pb right) => left.Value == right.Value;
		public static bool operator !=(pb left, pb right) => left.Value != right.Value;
		public static bool operator <(pb left, pb right) => left.Value < right.Value;
		public static bool operator <=(pb left, pb right) => left.Value <= right.Value;
		public static bool operator >(pb left, pb right) => left.Value > right.Value;
		public static bool operator >=(pb left, pb right) => left.Value >= right.Value;
        
		public static explicit operator pb(b other) => new(other.Value / 1125899906842624);
		public static explicit operator pb(kb other) => new(other.Value / 1099511627776);
		public static explicit operator pb(mb other) => new(other.Value / 1073741824);
		public static explicit operator pb(gb other) => new(other.Value / 1048576);
		public static explicit operator pb(tb other) => new(other.Value / 1024);
		public static explicit operator pb(B other) => new(other.Value / 140737488355328);
		public static explicit operator pb(KB other) => new(other.Value / 137438953472);
		public static explicit operator pb(MB other) => new(other.Value / 134217728);
		public static explicit operator pb(GB other) => new(other.Value / 131072);
		public static explicit operator pb(TB other) => new(other.Value / 128);
		public static explicit operator pb(PB other) => new(other.Value * 8);
        public static implicit operator pb(double value) => new pb(value);

		public override string ToString() => $"{Value} pb";
	}

	public struct B(double value) : IMeasurable<double>
	{
		public double Value { get; set; } = value;

		public static B operator +(B left, B right) => new(left.Value + right.Value);
		public static B operator -(B left, B right) => new(left.Value - right.Value);
		public static B operator *(B left, double right) => new(left.Value * right);
		public static B operator /(B left, double right) => new(left.Value / right);
		public static B operator /(B left, B right) => left.Value / right.Value;
        
		public static bool operator ==(B left, B right) => left.Value == right.Value;
		public static bool operator !=(B left, B right) => left.Value != right.Value;
		public static bool operator <(B left, B right) => left.Value < right.Value;
		public static bool operator <=(B left, B right) => left.Value <= right.Value;
		public static bool operator >(B left, B right) => left.Value > right.Value;
		public static bool operator >=(B left, B right) => left.Value >= right.Value;
        
		public static explicit operator B(b other) => new(other.Value / 8);
		public static explicit operator B(kb other) => new(other.Value * 128);
		public static explicit operator B(mb other) => new(other.Value * 131072);
		public static explicit operator B(gb other) => new(other.Value * 134217728);
		public static explicit operator B(tb other) => new(other.Value * 137438953472);
		public static explicit operator B(pb other) => new(other.Value * 140737488355328);
		public static explicit operator B(KB other) => new(other.Value * 1024);
		public static explicit operator B(MB other) => new(other.Value * 1048576);
		public static explicit operator B(GB other) => new(other.Value * 1073741824);
		public static explicit operator B(TB other) => new(other.Value * 1099511627776);
		public static explicit operator B(PB other) => new(other.Value * 1125899906842624);
        public static implicit operator B(double value) => new B(value);

		public override string ToString() => $"{Value} B";
	}

	public struct KB(double value) : IMeasurable<double>
	{
		public double Value { get; set; } = value;

		public static KB operator +(KB left, KB right) => new(left.Value + right.Value);
		public static KB operator -(KB left, KB right) => new(left.Value - right.Value);
		public static KB operator *(KB left, double right) => new(left.Value * right);
		public static KB operator /(KB left, double right) => new(left.Value / right);
		public static KB operator /(KB left, KB right) => left.Value / right.Value;
        
		public static bool operator ==(KB left, KB right) => left.Value == right.Value;
		public static bool operator !=(KB left, KB right) => left.Value != right.Value;
		public static bool operator <(KB left, KB right) => left.Value < right.Value;
		public static bool operator <=(KB left, KB right) => left.Value <= right.Value;
		public static bool operator >(KB left, KB right) => left.Value > right.Value;
		public static bool operator >=(KB left, KB right) => left.Value >= right.Value;
        
		public static explicit operator KB(b other) => new(other.Value / 8192);
		public static explicit operator KB(kb other) => new(other.Value / 8);
		public static explicit operator KB(mb other) => new(other.Value * 128);
		public static explicit operator KB(gb other) => new(other.Value * 131072);
		public static explicit operator KB(tb other) => new(other.Value * 134217728);
		public static explicit operator KB(pb other) => new(other.Value * 137438953472);
		public static explicit operator KB(B other) => new(other.Value / 1024);
		public static explicit operator KB(MB other) => new(other.Value * 1024);
		public static explicit operator KB(GB other) => new(other.Value * 1048576);
		public static explicit operator KB(TB other) => new(other.Value * 1073741824);
		public static explicit operator KB(PB other) => new(other.Value * 1099511627776);
        public static implicit operator KB(double value) => new KB(value);

		public override string ToString() => $"{Value} KB";
	}

	public struct MB(double value) : IMeasurable<double>
	{
		public double Value { get; set; } = value;

		public static MB operator +(MB left, MB right) => new(left.Value + right.Value);
		public static MB operator -(MB left, MB right) => new(left.Value - right.Value);
		public static MB operator *(MB left, double right) => new(left.Value * right);
		public static MB operator /(MB left, double right) => new(left.Value / right);
		public static MB operator /(MB left, MB right) => left.Value / right.Value;
        
		public static bool operator ==(MB left, MB right) => left.Value == right.Value;
		public static bool operator !=(MB left, MB right) => left.Value != right.Value;
		public static bool operator <(MB left, MB right) => left.Value < right.Value;
		public static bool operator <=(MB left, MB right) => left.Value <= right.Value;
		public static bool operator >(MB left, MB right) => left.Value > right.Value;
		public static bool operator >=(MB left, MB right) => left.Value >= right.Value;
        
		public static explicit operator MB(b other) => new(other.Value / 8388608);
		public static explicit operator MB(kb other) => new(other.Value / 8192);
		public static explicit operator MB(mb other) => new(other.Value / 8);
		public static explicit operator MB(gb other) => new(other.Value * 128);
		public static explicit operator MB(tb other) => new(other.Value * 131072);
		public static explicit operator MB(pb other) => new(other.Value * 134217728);
		public static explicit operator MB(B other) => new(other.Value / 1048576);
		public static explicit operator MB(KB other) => new(other.Value / 1024);
		public static explicit operator MB(GB other) => new(other.Value * 1024);
		public static explicit operator MB(TB other) => new(other.Value * 1048576);
		public static explicit operator MB(PB other) => new(other.Value * 1073741824);
        public static implicit operator MB(double value) => new MB(value);

		public override string ToString() => $"{Value} MB";
	}

	public struct GB(double value) : IMeasurable<double>
	{
		public double Value { get; set; } = value;

		public static GB operator +(GB left, GB right) => new(left.Value + right.Value);
		public static GB operator -(GB left, GB right) => new(left.Value - right.Value);
		public static GB operator *(GB left, double right) => new(left.Value * right);
		public static GB operator /(GB left, double right) => new(left.Value / right);
		public static GB operator /(GB left, GB right) => left.Value / right.Value;
        
		public static bool operator ==(GB left, GB right) => left.Value == right.Value;
		public static bool operator !=(GB left, GB right) => left.Value != right.Value;
		public static bool operator <(GB left, GB right) => left.Value < right.Value;
		public static bool operator <=(GB left, GB right) => left.Value <= right.Value;
		public static bool operator >(GB left, GB right) => left.Value > right.Value;
		public static bool operator >=(GB left, GB right) => left.Value >= right.Value;
        
		public static explicit operator GB(b other) => new(other.Value / 8589934592);
		public static explicit operator GB(kb other) => new(other.Value / 8388608);
		public static explicit operator GB(mb other) => new(other.Value / 8192);
		public static explicit operator GB(gb other) => new(other.Value / 8);
		public static explicit operator GB(tb other) => new(other.Value * 128);
		public static explicit operator GB(pb other) => new(other.Value * 131072);
		public static explicit operator GB(B other) => new(other.Value / 1073741824);
		public static explicit operator GB(KB other) => new(other.Value / 1048576);
		public static explicit operator GB(MB other) => new(other.Value / 1024);
		public static explicit operator GB(TB other) => new(other.Value * 1024);
		public static explicit operator GB(PB other) => new(other.Value * 1048576);
        public static implicit operator GB(double value) => new GB(value);

		public override string ToString() => $"{Value} GB";
	}

	public struct TB(double value) : IMeasurable<double>
	{
		public double Value { get; set; } = value;

		public static TB operator +(TB left, TB right) => new(left.Value + right.Value);
		public static TB operator -(TB left, TB right) => new(left.Value - right.Value);
		public static TB operator *(TB left, double right) => new(left.Value * right);
		public static TB operator /(TB left, double right) => new(left.Value / right);
		public static TB operator /(TB left, TB right) => left.Value / right.Value;
        
		public static bool operator ==(TB left, TB right) => left.Value == right.Value;
		public static bool operator !=(TB left, TB right) => left.Value != right.Value;
		public static bool operator <(TB left, TB right) => left.Value < right.Value;
		public static bool operator <=(TB left, TB right) => left.Value <= right.Value;
		public static bool operator >(TB left, TB right) => left.Value > right.Value;
		public static bool operator >=(TB left, TB right) => left.Value >= right.Value;
        
		public static explicit operator TB(b other) => new(other.Value / 8796093022208);
		public static explicit operator TB(kb other) => new(other.Value / 8589934592);
		public static explicit operator TB(mb other) => new(other.Value / 8388608);
		public static explicit operator TB(gb other) => new(other.Value / 8192);
		public static explicit operator TB(tb other) => new(other.Value / 8);
		public static explicit operator TB(pb other) => new(other.Value * 128);
		public static explicit operator TB(B other) => new(other.Value / 1099511627776);
		public static explicit operator TB(KB other) => new(other.Value / 1073741824);
		public static explicit operator TB(MB other) => new(other.Value / 1048576);
		public static explicit operator TB(GB other) => new(other.Value / 1024);
		public static explicit operator TB(PB other) => new(other.Value * 1024);
        public static implicit operator TB(double value) => new TB(value);

		public override string ToString() => $"{Value} TB";
	}

	public struct PB(double value) : IMeasurable<double>
	{
		public double Value { get; set; } = value;

		public static PB operator +(PB left, PB right) => new(left.Value + right.Value);
		public static PB operator -(PB left, PB right) => new(left.Value - right.Value);
		public static PB operator *(PB left, double right) => new(left.Value * right);
		public static PB operator /(PB left, double right) => new(left.Value / right);
		public static PB operator /(PB left, PB right) => left.Value / right.Value;
        
		public static bool operator ==(PB left, PB right) => left.Value == right.Value;
		public static bool operator !=(PB left, PB right) => left.Value != right.Value;
		public static bool operator <(PB left, PB right) => left.Value < right.Value;
		public static bool operator <=(PB left, PB right) => left.Value <= right.Value;
		public static bool operator >(PB left, PB right) => left.Value > right.Value;
		public static bool operator >=(PB left, PB right) => left.Value >= right.Value;
        
		public static explicit operator PB(b other) => new(other.Value / 9007199254740992);
		public static explicit operator PB(kb other) => new(other.Value / 8796093022208);
		public static explicit operator PB(mb other) => new(other.Value / 8589934592);
		public static explicit operator PB(gb other) => new(other.Value / 8388608);
		public static explicit operator PB(tb other) => new(other.Value / 8192);
		public static explicit operator PB(pb other) => new(other.Value / 8);
		public static explicit operator PB(B other) => new(other.Value / 1125899906842624);
		public static explicit operator PB(KB other) => new(other.Value / 1099511627776);
		public static explicit operator PB(MB other) => new(other.Value / 1073741824);
		public static explicit operator PB(GB other) => new(other.Value / 1048576);
		public static explicit operator PB(TB other) => new(other.Value / 1024);
        public static implicit operator PB(double value) => new PB(value);

		public override string ToString() => $"{Value} PB";
	}

}

public static class StorageCapacityExtensions
{
    public static b Sum(this IEnumerable<b> @this) => new b(@this.Sum(x => x.Value));
    public static b Average(this IEnumerable<b> @this) => new b(@this.Average(x => x.Value));

    public static kb Sum(this IEnumerable<kb> @this) => new kb(@this.Sum(x => x.Value));
    public static kb Average(this IEnumerable<kb> @this) => new kb(@this.Average(x => x.Value));

    public static mb Sum(this IEnumerable<mb> @this) => new mb(@this.Sum(x => x.Value));
    public static mb Average(this IEnumerable<mb> @this) => new mb(@this.Average(x => x.Value));

    public static gb Sum(this IEnumerable<gb> @this) => new gb(@this.Sum(x => x.Value));
    public static gb Average(this IEnumerable<gb> @this) => new gb(@this.Average(x => x.Value));

    public static tb Sum(this IEnumerable<tb> @this) => new tb(@this.Sum(x => x.Value));
    public static tb Average(this IEnumerable<tb> @this) => new tb(@this.Average(x => x.Value));

    public static pb Sum(this IEnumerable<pb> @this) => new pb(@this.Sum(x => x.Value));
    public static pb Average(this IEnumerable<pb> @this) => new pb(@this.Average(x => x.Value));

    public static B Sum(this IEnumerable<B> @this) => new B(@this.Sum(x => x.Value));
    public static B Average(this IEnumerable<B> @this) => new B(@this.Average(x => x.Value));

    public static KB Sum(this IEnumerable<KB> @this) => new KB(@this.Sum(x => x.Value));
    public static KB Average(this IEnumerable<KB> @this) => new KB(@this.Average(x => x.Value));

    public static MB Sum(this IEnumerable<MB> @this) => new MB(@this.Sum(x => x.Value));
    public static MB Average(this IEnumerable<MB> @this) => new MB(@this.Average(x => x.Value));

    public static GB Sum(this IEnumerable<GB> @this) => new GB(@this.Sum(x => x.Value));
    public static GB Average(this IEnumerable<GB> @this) => new GB(@this.Average(x => x.Value));

    public static TB Sum(this IEnumerable<TB> @this) => new TB(@this.Sum(x => x.Value));
    public static TB Average(this IEnumerable<TB> @this) => new TB(@this.Average(x => x.Value));

    public static PB Sum(this IEnumerable<PB> @this) => new PB(@this.Sum(x => x.Value));
    public static PB Average(this IEnumerable<PB> @this) => new PB(@this.Average(x => x.Value));

}

